const lang = {
  en: {
    signIn: "Sign In",
    signUp: "Sign Up",
    signOut: "Sign Out",
    newtoAstroGPT: "New to AstroGPT?",
    password: "Password",
    email: "Email Address",
    name: "Full Name",
    alreadyAcc: "Already have an account?",
    welcome: "Beyond the Stars",
    astroGPT: "PlutoAstro",
    finger: "Smart Spiritual Insights",
    gptSearch: "GPT Search",
    loginDescription:"Connect with astrologers, get real-time insights, generate natal charts, and discover your cosmic destiny.",
    explore: "BluBot",
    chat: "Chat with Astrologers",
    call: "Call to Astrologers",
    search: "Search for Astrologers",
    filter: "Filter",
    all: "All",
    topRated: "Top rated",
    offer: "Offer",
    vedic: "Vedic",
    numerology: "Numerology",
    tarot: "Tarot",
    faceReading: "Face Reading",
    vastu: "Vastu",
    lifeCoach: "Life Coach",
    psychologist: "Psychologist",
    palmistry: "Palmistry",
    orders: "Orders",
    exp: "Exp",
    years: "Years",
    min: "min",
    horoTitle: "Daily Horoscope",
    horoDesc:
      "Receive daily horoscope predictions and personalized astrological insights to help you make informed decisions, strengthen relationships, and unlock new opportunities.",
    Aries: "Aries",
    Taurus: "Taurus",
    Gemini: "Gemini",
    Cancer: "Cancer",
    Leo: "Leo",
    Virgo: "Virgo",
    Libra: "Libra",
    Scorpio: "Scorpio",
    Sagittarius: "Sagittarius",
    Capricorn: "Capricorn",
    Aquarius: "Aquarius",
    Pisces: "Pisces",
    ourAstrologers: "Our Astrologers",
    astroDesc: "13000+ Best Astrologers from India for Online Consultation",
    zodiacTitle: "Know Your Zodiac Sign",
    zodiacDesc:
      "A brief yet insightful exploration of the distinct traits and influences associated with each astrological symbol, providing valuable insights into personality and life paths based on birth dates. Delve into the mysteries of astrology and uncover the hidden depths of your zodiac identity.",
    zodiacBirth: "Date of Birth",
    zodiacTime: "Time Of Birth",
    zodiacPlace: "Place Of Birth",
    zodiacFind: "FIND",
    CHAT: "CHAT",
    CALL: "CALL",
    SIGNOUT: "SIGNOUT",
    FOLLOWING: "FOLLOWING",
    ASTROBOT: "Pluto BOT",
    LOGIN: "LOGIN",
    KUNDLIGPT: "KUNDLI GPT",
    yourHoroscope: "Your Horoscope",
    todaysHoroof: " Todays Horoscope of",
    horobottomtitle1: "Today's horoscope for zodiac signs",
    horobottomtitle2: "Unlock Your Cosmic Destiny with AstroGPT Horoscopes",
    horobottomdesc1:
      " Welcome to the realm where stars align and destinies unfold. Dive into the celestial mysteries with AstroGPT Horoscopes, where each prediction is a glimpse into the cosmic tapestry of your life. Our astrological insights, powered by cutting-edge GPT technology, guidance and illumination as you navigate the celestial currents. Step into the world of AstroGPT Horoscopes and discover the wisdom written in the stars.",
    horobottomtitle3: "About AstroGPT Horoscope Prediction:",
    horobottomdesc2:
      "Our AstroGPT Horoscope Prediction brings the timeless wisdom of astrology into the digital age. Crafted by our advanced GPT models, our horoscopes offer personalized insights into your past, present, and future. While our predictions may not be grounded in traditional astrological practices, they serve as guiding lights in your journey through life's ever-changing landscape. Explore the cosmic whispers with AstroGPT Horoscopes and unlock the secrets of the universe",
    horobottomtitle4: "How Today's Horoscope Can Guide You:",
    horopoint1:
      " Gain insights into potential opportunities and challenges that may arise throughout your day.",
    horopoint2:
      " Receive personalized guidance based on your zodiac sign, helping you make informed decisions.",
    horopoint3:
      " Find clarity and direction in various aspects of your life, including love, career, health, and personal growth.",
    horopoint4:
      "Use your horoscope as a celestial compass to navigate life's twists and turns with confidence.",
    horopoint5:
      "Embrace the wisdom of the stars and uncover the hidden meanings behind daily events.",
    horopoint6:
      "  Stay attuned to the cosmic energies surrounding you and make the most of each moment.",

    astroKundli: "Pluto Kundli",
    astroBot: "Pluto Bot",
    getAstroInsights: "Get Astro Insights",
    inputname: "Name",
    birthPlace: "Birth Place",
    birthDistrict: "Birth District",
    birthTime: "Birth Date & Time",
    gender: "Gender",
    male: "Male",
    female: "Female",
    language: "Language",
    notfollowing: "You are not following anyone!",
    expFollow: "Explore Astrologers",
    following: "Following",
    clearFollow: "Clear Follow",
    unfollow: "Unfollow",
    ABOUT: "ABOUT",
  },
  de: {
    signIn: "Anmelden",
    signUp: "Registrieren",
    signOut: "Abmelden",
    newtoAstroGPT: "Neu bei AstroGPT?",
    password: "Passwort",
    email: "E-Mail-Adresse",
    name: "Vollständiger Name",
    alreadyAcc: "Haben Sie bereits ein Konto?",
    welcome: "Jenseits der Sterne",
    astroGPT: "PlutoAstro",
    finger: "Intelligente spirituelle Einblicke",
    gptSearch: "GPT Suche",
    loginDescription:"Verbinden Sie sich mit Astrologen, erhalten Sie Echtzeit-Einblicke, erstellen Sie Geburtshoroskope und entdecken Sie Ihr kosmisches Schicksal.",
    explore: "BluBot",
    chat: "Chat mit Astrologen",
    call: "Anruf zu Astrologen",
    search: "Suche nach Astrologen",
    filter: "Filter",
    all: "Alle",
    topRated: "Top bewertet",
    offer: "Angebot",
    vedic: "Vedisch",
    numerology: "Numerologie",
    tarot: "Tarot",
    faceReading: "Gesichtslesen",
    vastu: "Vastu",
    lifeCoach: "Lebensberater",
    psychologist: "Psychologe",
    palmistry: "Handflächenlesen",
    orders: "Bestellungen",
    exp: "Erf",
    years: "Jahre",
    min: "Min",
    horoTitle: "Tageshoroskop",
    horoDesc:
      "Erhalten Sie tägliche Horoskopvorhersagen und personalisierte astrologische Einblicke, die Ihnen helfen, fundierte Entscheidungen zu treffen, Beziehungen zu stärken und neue Möglichkeiten zu erschließen.",
    Aries: "Widder",
    Taurus: "Stier",
    Gemini: "Zwillinge",
    Cancer: "Krebs",
    Leo: "Löwe",
    Virgo: "Jungfrau",
    Libra: "Waage",
    Scorpio: "Skorpion",
    Sagittarius: "Schütze",
    Capricorn: "Steinbock",
    Aquarius: "Wassermann",
    Pisces: "Fische",
    ourAstrologers: "Unsere Astrologen",
    astroDesc: "13000+ Beste Astrologen aus Indien für Online-Beratung",
    zodiacTitle: "Erfahren Sie Ihr Sternzeichen",
    zodiacDesc:
      "Eine kurze, aber aufschlussreiche Erkundung der unterschiedlichen Merkmale und Einflüsse, die mit jedem astrologischen Symbol verbunden sind, und die wertvolle Einblicke in Persönlichkeit und Lebenswege basierend auf Geburtsdaten bietet.",
    zodiacBirth: "Geburtsdatum",
    zodiacTime: "Geburtszeit",
    zodiacPlace: "Geburtsort",
    zodiacFind: "FINDEN",
    CHAT: "CHAT",
    CALL: "ANRUF",
    SIGNOUT: "ABMELDEN",
    FOLLOWING: "FOLGT",
    ASTROBOT: "Pluto BOT",
    LOGIN: "ANMELDEN",
    KUNDLIGPT: "KUNDLI GPT",
    yourHoroscope: "Ihr Horoskop",
    todaysHoroof: " Heutiges Horoskop von",
    horobottomtitle1: "Heutiges Horoskop für Sternzeichen",
    horobottomtitle2: "Entfesseln Sie Ihr kosmisches Schicksal mit AstroGPT Horoskopen",
    horobottomdesc1:
      "Willkommen im Reich, wo sich die Sterne ausrichten und sich das Schicksal entfaltet. Tauchen Sie ein in die himmlischen Geheimnisse mit AstroGPT Horoskopen.",
    horobottomtitle3: "Über AstroGPT Horoskopvorhersage:",
    horobottomdesc2:
      "Unsere AstroGPT Horoskopvorhersage bringt die zeitlose Weisheit der Astrologie ins digitale Zeitalter.",
    horobottomtitle4: "Wie kann Sie das heutige Horoskop leiten:",
    horopoint1:
      "Gewinnen Sie Einblicke in potenzielle Möglichkeiten und Herausforderungen, die im Laufe Ihres Tages auftreten können.",
    horopoint2:
      "Erhalten Sie personalisierte Anleitung basierend auf Ihrem Sternzeichen.",
    horopoint3:
      "Finden Sie Klarheit und Richtung in verschiedenen Aspekten Ihres Lebens.",
    horopoint4:
      "Nutzen Sie Ihr Horoskop als himmlischen Kompass.",
    horopoint5:
      "Umarmen Sie die Weisheit der Sterne.",
    horopoint6:
      "Bleiben Sie mit den kosmischen Energien um Sie herum verbunden.",
    astroKundli: "Pluto Kundli",
    astroBot: "Pluto Bot",
    getAstroInsights: "Astro Einblicke erhalten",
    inputname: "Name",
    birthPlace: "Geburtsort",
    birthDistrict: "Geburtsbezirk",
    birthTime: "Geburtsdatum & Zeit",
    gender: "Geschlecht",
    male: "Männlich",
    female: "Weiblich",
    language: "Sprache",
    notfollowing: "Sie folgen niemandem!",
    expFollow: "Astrologen erkunden",
    following: "Folgt",
    clearFollow: "Folgen löschen",
    unfollow: "Entfolgen",
    ABOUT: "ÜBER",
  },
  it: {
    signIn: "Accedi",
    signUp: "Registrati",
    signOut: "Esci",
    newtoAstroGPT: "Nuovo su AstroGPT?",
    password: "Password",
    email: "Indirizzo email",
    name: "Nome completo",
    alreadyAcc: "Hai già un account?",
    welcome: "Oltre le Stelle",
    astroGPT: "PlutoAstro",
    finger: "Approfondimenti Spirituali Intelligenti",
    gptSearch: "Ricerca GPT",
    loginDescription:"Connettiti con gli astrologi, ottieni approfondimenti in tempo reale, genera carte natali e scopri il tuo destino cosmico.",
    explore: "BluBot",
    chat: "Chatta con Astrologi",
    call: "Chiama Astrologi",
    search: "Cerca Astrologi",
    filter: "Filtro",
    all: "Tutti",
    topRated: "Più votati",
    offer: "Offerta",
    vedic: "Vedico",
    numerology: "Numerologia",
    tarot: "Tarocchi",
    faceReading: "Lettura del Viso",
    vastu: "Vastu",
    lifeCoach: "Life Coach",
    psychologist: "Psicologo",
    palmistry: "Chiromanzia",
    orders: "Ordini",
    exp: "Esp",
    years: "Anni",
    min: "min",
    horoTitle: "Oroscopo Giornaliero",
    horoDesc:
      "Ricevi previsioni dell'oroscopo quotidiano e approfondimenti astrologici personalizzati per aiutarti a prendere decisioni informate, rafforzare le relazioni e sbloccare nuove opportunità.",
    Aries: "Ariete",
    Taurus: "Toro",
    Gemini: "Gemelli",
    Cancer: "Cancro",
    Leo: "Leone",
    Virgo: "Vergine",
    Libra: "Bilancia",
    Scorpio: "Scorpione",
    Sagittarius: "Sagittario",
    Capricorn: "Capricorno",
    Aquarius: "Acquario",
    Pisces: "Pesci",
    ourAstrologers: "I Nostri Astrologi",
    astroDesc: "13000+ Migliori Astrologi dall'India per Consultazione Online",
    zodiacTitle: "Scopri il Tuo Segno Zodiacale",
    zodiacDesc:
      "Un'esplorazione breve ma approfondita dei tratti distintivi e delle influenze associate a ciascun simbolo astrologico, fornendo preziose intuizioni sulla personalità e sui percorsi di vita basati sulle date di nascita.",
    zodiacBirth: "Data di Nascita",
    zodiacTime: "Ora di Nascita",
    zodiacPlace: "Luogo di Nascita",
    zodiacFind: "TROVA",
    CHAT: "CHAT",
    CALL: "CHIAMA",
    SIGNOUT: "ESCI",
    FOLLOWING: "SEGUENDO",
    ASTROBOT: "Pluto BOT",
    LOGIN: "ACCEDI",
    KUNDLIGPT: "KUNDLI GPT",
    yourHoroscope: "Il Tuo Oroscopo",
    todaysHoroof: " Oroscopo di oggi di",
    horobottomtitle1: "Oroscopo di oggi per i segni zodiacali",
    horobottomtitle2: "Sblocca il Tuo Destino Cosmico con gli Oroscopi AstroGPT",
    horobottomdesc1:
      "Benvenuto nel regno dove le stelle si allineano e i destini si svelano. Immergiti nei misteri celesti con gli Oroscopi AstroGPT.",
    horobottomtitle3: "Informazioni sulla Previsione dell'Oroscopo AstroGPT:",
    horobottomdesc2:
      "La nostra Previsione dell'Oroscopo AstroGPT porta l'atemporale saggezza dell'astrologia nell'era digitale.",
    horobottomtitle4: "Come l'Oroscopo di Oggi Può Guidarti:",
    horopoint1:
      "Ottieni approfondimenti su potenziali opportunità e sfide che possono sorgere durante la giornata.",
    horopoint2:
      "Ricevi una guida personalizzata basata sul tuo segno zodiacale.",
    horopoint3:
      "Trova chiarezza e direzione in vari aspetti della tua vita.",
    horopoint4:
      "Usa il tuo oroscopo come una bussola celeste.",
    horopoint5:
      "Abbraccia la saggezza delle stelle.",
    horopoint6:
      "Rimani in sintonia con le energie cosmiche che ti circondano.",
    astroKundli: "Pluto Kundli",
    astroBot: "Pluto Bot",
    getAstroInsights: "Ottieni Approfondimenti Astro",
    inputname: "Nome",
    birthPlace: "Luogo di nascita",
    birthDistrict: "Distretto di nascita",
    birthTime: "Data e Ora di nascita",
    gender: "Genere",
    male: "Maschile",
    female: "Femminile",
    language: "Lingua",
    notfollowing: "Non stai seguendo nessuno!",
    expFollow: "Esplora Astrologi",
    following: "Seguendo",
    clearFollow: "Cancella Seguiti",
    unfollow: "Smetti di seguire",
    ABOUT: "INFORMAZIONI",
  },
  ar: {
    signIn: "تسجيل الدخول",
    signUp: "إنشاء حساب",
    signOut: "تسجيل الخروج",
    newtoAstroGPT: "جديد على AstroGPT؟",
    password: "كلمة المرور",
    email: "عنوان البريد الإلكتروني",
    name: "الاسم الكامل",
    alreadyAcc: "هل لديك حساب بالفعل؟",
    welcome: "ما وراء النجوم",
    astroGPT: "PlutoAstro",
    finger: "رؤى روحية ذكية",
    gptSearch: "بحث GPT",
    loginDescription:"تواصل مع المنجمين، احصل على رؤى في الوقت الفعلي، وأنشئ مواليد واكتشف مصيرك الكوني.",
    explore: "BluBot",
    chat: "دردشة مع المنجمين",
    call: "اتصال بالمنجمين",
    search: "البحث عن المنجمين",
    filter: "تصفية",
    all: "الكل",
    topRated: "الأعلى تقييماً",
    offer: "عرض",
    vedic: "فيدي",
    numerology: "علم الأعداد",
    tarot: "تاروت",
    faceReading: "قراءة الوجه",
    vastu: "فاستو",
    lifeCoach: "مدرب حياة",
    psychologist: "طبيب نفسي",
    palmistry: "قراءة الكف",
    orders: "الطلبات",
    exp: "خبرة",
    years: "سنوات",
    min: "دقيقة",
    horoTitle: "الأبراج اليومية",
    horoDesc:
      "احصل على توقعات الأبراج اليومية ورؤى فلكية مخصصة لمساعدتك في اتخاذ قرارات مستنيرة، وتعزيز العلاقات، وفتح فرص جديدة.",
    Aries: "الحمل",
    Taurus: "الثور",
    Gemini: "الجوزاء",
    Cancer: "السرطان",
    Leo: "الأسد",
    Virgo: "العذراء",
    Libra: "الميزان",
    Scorpio: "العقرب",
    Sagittarius: "القوس",
    Capricorn: "الجدي",
    Aquarius: "الدلو",
    Pisces: "الحوت",
    ourAstrologers: "منجمونا",
    astroDesc: "أكثر من 13000 من أفضل المنجمين من الهند للاستشارة عبر الإنترنت",
    zodiacTitle: "اعرف برجك",
    zodiacDesc:
      "استكشاف موجز ولكن ثاقب للسمات والتأثيرات المميزة المرتبطة بكل رمز فلكي، يوفر رؤى قيمة حول الشخصية ومسارات الحياة بناءً على تواريخ الميلاد.",
    zodiacBirth: "تاريخ الميلاد",
    zodiacTime: "وقت الميلاد",
    zodiacPlace: "مكان الميلاد",
    zodiacFind: "ابحث",
    CHAT: "دردشة",
    CALL: "اتصال",
    SIGNOUT: "خروج",
    FOLLOWING: "متابعة",
    ASTROBOT: "Pluto بوت",
    LOGIN: "دخول",
    KUNDLIGPT: "KUNDLI GPT",
    yourHoroscope: "برجك",
    todaysHoroof: " برج اليوم لـ",
    horobottomtitle1: "الأبراج اليوم للعلامات الزodiacية",
    horobottomtitle2: "اكتشف مصيرك الكوني مع أبراج AstroGPT",
    horobottomdesc1:
      "مرحباً بك في المملكة حيث تصطف النجوم وتتجلى المصاير. اغمر في الأسرار السماوية مع أبراج AstroGPT.",
    horobottomtitle3: "حول توقعات أبراج AstroGPT:",
    horobottomdesc2:
      "توقعات أبراج AstroGPT لدينا تجلب حكمة التنجيم الخالدة إلى العصر الرقمي.",
    horobottomtitle4: "كيف يمكن لبرج اليوم أن يرشدك:",
    horopoint1:
      "احصل على رؤى حول الفرص والتحديات المحتملة التي قد تظهر طوال يومك.",
    horopoint2:
      "احصل على إرشادات مخصصة بناءً على برجك.",
    horopoint3:
      "اعثر على الوضوح والاتجاه في جوانب مختلفة من حياتك.",
    horopoint4:
      "استخدم برجك كبوصلة سماوية.",
    horopoint5:
      "اعتنق حكمة النجوم.",
    horopoint6:
      "ابق منسجماً مع الطاقات الكونية من حولك.",
    astroKundli: "Pluto Kundli",
    astroBot: "Pluto Bot",
    getAstroInsights: "احصل على رؤى فلكية",
    inputname: "الاسم",
    birthPlace: "مكان الميلاد",
    birthDistrict: "منطقة الميلاد",
    birthTime: "تاريخ ووقت الميلاد",
    gender: "الجنس",
    male: "ذكر",
    female: "أنثى",
    language: "اللغة",
    notfollowing: "أنت لا تتبع أحداً!",
    expFollow: "استكشف المنجمين",
    following: "متابعة",
    clearFollow: "مسح المتابعة",
    unfollow: "إلغاء المتابعة",
    ABOUT: "حول",
  },
  fr: {
    signIn: "Se connecter",
    signUp: "S'inscrire",
    signOut: "Se déconnecter",
    newtoAstroGPT: "Nouveau sur AstroGPT?",
    password: "Mot de passe",
    email: "Adresse e-mail",
    name: "Nom complet",
    alreadyAcc: "Vous avez déjà un compte?",
    welcome: "Au-delà des Étoiles",
    astroGPT: "PlutoAstro",
    finger: "Informations Spirituelles Intelligentes",
    gptSearch: "Recherche GPT",
    loginDescription:"Connectez-vous avec des astrologues, obtenez des informations en temps réel, générez des thèmes natals et découvrez votre destin cosmique.",
    explore: "BluBot",
    chat: "Discuter avec Astrologues",
    call: "Appeler Astrologues",
    search: "Rechercher Astrologues",
    filter: "Filtre",
    all: "Tous",
    topRated: "Mieux notés",
    offer: "Offre",
    vedic: "Védique",
    numerology: "Numérologie",
    tarot: "Tarot",
    faceReading: "Lecture du Visage",
    vastu: "Vastu",
    lifeCoach: "Coach de Vie",
    psychologist: "Psychologue",
    palmistry: "Chiromancie",
    orders: "Commandes",
    exp: "Exp",
    years: "Ans",
    min: "min",
    horoTitle: "Horoscope Quotidien",
    horoDesc:
      "Recevez des prédictions d'horoscope quotidiennes et des informations astrologiques personnalisées pour vous aider à prendre des décisions éclairées, renforcer les relations et débloquer de nouvelles opportunités.",
    Aries: "Bélier",
    Taurus: "Taureau",
    Gemini: "Gémeaux",
    Cancer: "Cancer",
    Leo: "Lion",
    Virgo: "Vierge",
    Libra: "Balance",
    Scorpio: "Scorpion",
    Sagittarius: "Sagittaire",
    Capricorn: "Capricorne",
    Aquarius: "Verseau",
    Pisces: "Poissons",
    ourAstrologers: "Nos Astrologues",
    astroDesc: "13000+ Meilleurs Astrologues de l'Inde pour Consultation en Ligne",
    zodiacTitle: "Découvrez Votre Signe du Zodiaque",
    zodiacDesc:
      "Une exploration brève mais perspicace des traits distinctifs et des influences associés à chaque symbole astrologique, fournissant des informations précieuses sur la personnalité et les parcours de vie basés sur les dates de naissance.",
    zodiacBirth: "Date de Naissance",
    zodiacTime: "Heure de Naissance",
    zodiacPlace: "Lieu de Naissance",
    zodiacFind: "TROUVER",
    CHAT: "CHAT",
    CALL: "APPELER",
    SIGNOUT: "DÉCONNECTER",
    FOLLOWING: "ABONNEMENTS",
    ASTROBOT: "Pluto BOT",
    LOGIN: "CONNEXION",
    KUNDLIGPT: "KUNDLI GPT",
    yourHoroscope: "Votre Horoscope",
    todaysHoroof: " Horoscope du jour de",
    horobottomtitle1: "Horoscope du jour pour les signes du zodiaque",
    horobottomtitle2: "Débloquez Votre Destin Cosmique avec les Horoscopes AstroGPT",
    horobottomdesc1:
      "Bienvenue dans le royaume où les étoiles s'alignent et les destins se déploient. Plongez dans les mystères célestes avec les Horoscopes AstroGPT.",
    horobottomtitle3: "À propos de la Prédiction d'Horoscope AstroGPT:",
    horobottomdesc2:
      "Notre Prédiction d'Horoscope AstroGPT apporte la sagesse intemporelle de l'astrologie à l'ère numérique.",
    horobottomtitle4: "Comment l'Horoscope du Jour Peut Vous Guider:",
    horopoint1:
      "Obtenez des informations sur les opportunités et défis potentiels qui peuvent survenir tout au long de votre journée.",
    horopoint2:
      "Recevez des conseils personnalisés basés sur votre signe du zodiaque.",
    horopoint3:
      "Trouvez clarté et direction dans divers aspects de votre vie.",
    horopoint4:
      "Utilisez votre horoscope comme une boussole céleste.",
    horopoint5:
      "Embrassez la sagesse des étoiles.",
    horopoint6:
      "Restez à l'écoute des énergies cosmiques qui vous entourent.",
    astroKundli: "Pluto Kundli",
    astroBot: "Pluto Bot",
    getAstroInsights: "Obtenir des Informations Astro",
    inputname: "Nom",
    birthPlace: "Lieu de naissance",
    birthDistrict: "District de naissance",
    birthTime: "Date et heure de naissance",
    gender: "Genre",
    male: "Masculin",
    female: "Féminin",
    language: "Langue",
    notfollowing: "Vous ne suivez personne!",
    expFollow: "Explorer les Astrologues",
    following: "Abonnements",
    clearFollow: "Effacer les Abonnements",
    unfollow: "Se désabonner",
    ABOUT: "À PROPOS",
  },
  pt: {
    signIn: "Entrar",
    signUp: "Cadastrar",
    signOut: "Sair",
    newtoAstroGPT: "Novo no AstroGPT?",
    password: "Senha",
    email: "Endereço de e-mail",
    name: "Nome completo",
    alreadyAcc: "Já tem uma conta?",
    welcome: "Além das Estrelas",
    astroGPT: "PlutoAstro",
    finger: "Insights Espirituais Inteligentes",
    gptSearch: "Busca GPT",
    loginDescription:"Conecte-se com astrólogos, obtenha insights em tempo real, gere mapas natais e descubra seu destino cósmico.",
    explore: "BluBot",
    chat: "Conversar com Astrólogos",
    call: "Ligar para Astrólogos",
    search: "Buscar Astrólogos",
    filter: "Filtro",
    all: "Todos",
    topRated: "Melhor avaliados",
    offer: "Oferta",
    vedic: "Védico",
    numerology: "Numerologia",
    tarot: "Tarô",
    faceReading: "Leitura Facial",
    vastu: "Vastu",
    lifeCoach: "Coach de Vida",
    psychologist: "Psicólogo",
    palmistry: "Quiromancia",
    orders: "Pedidos",
    exp: "Exp",
    years: "Anos",
    min: "min",
    horoTitle: "Horóscopo Diário",
    horoDesc:
      "Receba previsões de horóscopo diárias e insights astrológicos personalizados para ajudá-lo a tomar decisões informadas, fortalecer relacionamentos e desbloquear novas oportunidades.",
    Aries: "Áries",
    Taurus: "Touro",
    Gemini: "Gêmeos",
    Cancer: "Câncer",
    Leo: "Leão",
    Virgo: "Virgem",
    Libra: "Libra",
    Scorpio: "Escorpião",
    Sagittarius: "Sagitário",
    Capricorn: "Capricórnio",
    Aquarius: "Aquário",
    Pisces: "Peixes",
    ourAstrologers: "Nossos Astrólogos",
    astroDesc: "13000+ Melhores Astrólogos da Índia para Consulta Online",
    zodiacTitle: "Conheça Seu Signo do Zodíaco",
    zodiacDesc:
      "Uma exploração breve, mas perspicaz, dos traços distintivos e influências associados a cada símbolo astrológico, fornecendo insights valiosos sobre personalidade e caminhos de vida baseados em datas de nascimento.",
    zodiacBirth: "Data de Nascimento",
    zodiacTime: "Hora de Nascimento",
    zodiacPlace: "Local de Nascimento",
    zodiacFind: "ENCONTRAR",
    CHAT: "CHAT",
    CALL: "LIGAR",
    SIGNOUT: "SAIR",
    FOLLOWING: "SEGUINDO",
    ASTROBOT: "Pluto BOT",
    LOGIN: "ENTRAR",
    KUNDLIGPT: "KUNDLI GPT",
    yourHoroscope: "Seu Horóscopo",
    todaysHoroof: " Horóscopo de hoje de",
    horobottomtitle1: "Horóscopo de hoje para signos do zodíaco",
    horobottomtitle2: "Desbloqueie Seu Destino Cósmico com Horóscopos AstroGPT",
    horobottomdesc1:
      "Bem-vindo ao reino onde as estrelas se alinham e os destinos se desdobram. Mergulhe nos mistérios celestes com Horóscopos AstroGPT.",
    horobottomtitle3: "Sobre a Previsão de Horóscopo AstroGPT:",
    horobottomdesc2:
      "Nossa Previsão de Horóscopo AstroGPT traz a sabedoria atemporal da astrologia para a era digital.",
    horobottomtitle4: "Como o Horóscopo de Hoje Pode Guiá-lo:",
    horopoint1:
      "Obtenha insights sobre oportunidades e desafios potenciais que podem surgir ao longo do seu dia.",
    horopoint2:
      "Receba orientações personalizadas com base no seu signo do zodíaco.",
    horopoint3:
      "Encontre clareza e direção em vários aspectos da sua vida.",
    horopoint4:
      "Use seu horóscopo como uma bússola celestial.",
    horopoint5:
      "Abrace a sabedoria das estrelas.",
    horopoint6:
      "Mantenha-se sintonizado com as energias cósmicas ao seu redor.",
    astroKundli: "Pluto Kundli",
    astroBot: "Pluto Bot",
    getAstroInsights: "Obter Insights de Astro",
    inputname: "Nome",
    birthPlace: "Local de nascimento",
    birthDistrict: "Distrito de nascimento",
    birthTime: "Data e hora de nascimento",
    gender: "Gênero",
    male: "Masculino",
    female: "Feminino",
    language: "Idioma",
    notfollowing: "Você não está seguindo ninguém!",
    expFollow: "Explorar Astrólogos",
    following: "Seguindo",
    clearFollow: "Limpar Seguindo",
    unfollow: "Deixar de seguir",
    ABOUT: "SOBRE",
  },
  ja: {
    signIn: "サインイン",
    signUp: "サインアップ",
    signOut: "サインアウト",
    newtoAstroGPT: "アストロGPT は初めてですか？",
    password: "パスワード",
    email: "メールアドレス",
    name: "フルネーム",
    alreadyAcc: "すでにアカウントをお持ちですか？",
    welcome: "ようこそ",
    astroGPT: "アストロGPT",
    finger: "宇宙への指標",
    gptSearch: "GPT 検索",
    loginDescription:
      "占星術師とつながり、シームレスにチャットし、パーソナライズされた星座占いを入手し、直感的なチャットボットと一緒に今日から宇宙の旅を始めましょう",
    explore: "探検する",
    chat: "占星術師とチャット",
    call: "占星術師に電話",
    search: "占星術師を検索",
    filter: "フィルター",
    all: "すべて",
    topRated: "トップ評価",
    offer: "オファー",
    vedic: "ヴェーダ",
    numerology: "数秘術",
    tarot: "タロット",
    faceReading: "顔の読み取り",
    vastu: "ヴァーストゥ",
    lifeCoach: "ライフコーチ",
    psychologist: "心理学者",
    palmistry: "手相学",
    orders: "注文",
    exp: "経験",
    years: "年",
    min: "分",
    horoTitle: "デイリーホロスコープ",
    horoDesc:
      "包括的なホロスコープセクションで占星術の神秘的な世界に飛び込んでください。星に書かれた秘密を発見し、あなたの人格、関係、将来についての洞察を解き放ちます。",
    Aries: "牡羊座",
    Taurus: "牡牛座",
    Gemini: "双子座",
    Cancer: "蟹座",
    Leo: "獅子座",
    Virgo: "乙女座",
    Libra: "天秤座",
    Scorpio: "蠍座",
    Sagittarius: "射手座",
    Capricorn: "山羊座",
    Aquarius: "水瓶座",
    Pisces: "魚座",
    ourAstrologers: "私たちの占星術師",
    astroDesc: "オンライン相談のためのインドのベスト占星術師13000人以上",
    zodiacTitle: "あなたの星座を知る",
    zodiacDesc:
      "各占星術の記号に関連付けられた独特の特徴と影響についての簡潔で洞察に富んだ探求は、誕生日に基づいた個性と人生の道に関する貴重な洞察を提供します。",
    zodiacBirth: "生年月日",
    zodiacTime: "出生時間",
    zodiacPlace: "出生地",
    zodiacFind: "検索",
    CHAT: "チャット",
    CALL: "通話",
    SIGNOUT: "サインアウト",
    FOLLOWING: "フォロー中",
    ASTROBOT: "アストロボット",
    KUNDLIGPT: "クンドリ GPT",
    LOGIN: "ログイン",
    astroKundli: "アストロクンドリ",
    astroBot: "アストロボット",
    yourHoroscope: "あなたの星座占い",
    todaysHoroof: " 今日の星座占い：",
    horobottomtitle1: "星座占い",
    horobottomtitle2: "AstroGPTのホロスコープで宇宙の運命を解き放ちます",
    horobottomdesc1:
      "星が一列になり、運命が展開される領域へようこそ。 AstroGPTホロスコープで星座占いの天体の秘密に飛び込んでください。",
    horobottomtitle3: "AstroGPTホロスコープ予測について：",
    horobottomdesc2:
      "AstroGPTホロスコープ予測は、古代の知恵をデジタル時代にもたらします。",
    horobottomtitle4: "今日のホロスコープがあなたを導く方法：",
    horopoint1: "一日中起こり得る潜在的な機会や課題についての洞察を得ます。",
    horopoint2:
      "あなたの星座に基づいて個別のガイダンスを受け取り、情報に基づいた決定を行います。",
    horopoint3:
      "愛情、キャリア、健康、個人の成長など、さまざまな面でクラリティと方向性を見つけます。",
    horopoint4:
      "あなたのホロスコープを天の羅針盤として使用し、自信を持って人生の曲がり角を進みます。",
    horopoint5:
      "星の知恵を受け入れ、日常の出来事の裏に隠された意味を見つけ出します。",
    horopoint6:
      "周りの宇宙のエネルギーに敏感になり、それぞれの瞬間を最大限に活用します。",
    getAstroInsights: "アストロインサイトを取得する",
    inputname: "名前",
    birthPlace: "出生地",
    birthDistrict: "出生地区",
    birthTime: "生年月日と時間",
    gender: "性別",
    male: "男性",
    female: "女性",
    language: "言語",
    notfollowing: "誰もフォローしていません！",
    expFollow: "占星術師を探す",
    following: "フォロー中",
    clearFollow: "フォローをクリア",
    unfollow: "フォロー解除",
    ABOUT: "約",
  },
  ru: {
    signIn: "Войти",
    signUp: "Зарегистрироваться",
    signOut: "Выйти",
    newtoAstroGPT: "Впервые на AstroGPT?",
    password: "Пароль",
    email: "Адрес электронной почты",
    name: "Полное имя",
    alreadyAcc: "У вас уже есть аккаунт?",
    welcome: "За пределами Звезд",
    astroGPT: "PlutoAstro",
    finger: "Умные духовные инсайты",
    gptSearch: "Поиск GPT",
    loginDescription:"Свяжитесь с астрологами, получите инсайты в реальном времени, создайте натальные карты и откройте свою космическую судьбу.",
    explore: "BluBot",
    chat: "Чат с Астрологами",
    call: "Звонок Астрологам",
    search: "Поиск Астрологов",
    filter: "Фильтр",
    all: "Все",
    topRated: "Лучшие",
    offer: "Предложение",
    vedic: "Ведический",
    numerology: "Нумерология",
    tarot: "Таро",
    faceReading: "Чтение лица",
    vastu: "Васту",
    lifeCoach: "Лайф-коуч",
    psychologist: "Психолог",
    palmistry: "Хиромантия",
    orders: "Заказы",
    exp: "Опыт",
    years: "Лет",
    min: "мин",
    horoTitle: "Ежедневный Гороскоп",
    horoDesc:
      "Получайте ежедневные предсказания гороскопа и персонализированные астрологические инсайты, чтобы принимать обоснованные решения, укреплять отношения и открывать новые возможности.",
    Aries: "Овен",
    Taurus: "Телец",
    Gemini: "Близнецы",
    Cancer: "Рак",
    Leo: "Лев",
    Virgo: "Дева",
    Libra: "Весы",
    Scorpio: "Скорпион",
    Sagittarius: "Стрелец",
    Capricorn: "Козерог",
    Aquarius: "Водолей",
    Pisces: "Рыбы",
    ourAstrologers: "Наши Астрологи",
    astroDesc: "13000+ Лучших Астрологов из Индии для Онлайн Консультаций",
    zodiacTitle: "Узнайте Ваш Знак Зодиака",
    zodiacDesc:
      "Краткое, но проницательное исследование отличительных черт и влияний, связанных с каждым астрологическим символом, предоставляющее ценные инсайты о личности и жизненных путях на основе дат рождения.",
    zodiacBirth: "Дата Рождения",
    zodiacTime: "Время Рождения",
    zodiacPlace: "Место Рождения",
    zodiacFind: "НАЙТИ",
    CHAT: "ЧАТ",
    CALL: "ЗВОНОК",
    SIGNOUT: "ВЫЙТИ",
    FOLLOWING: "ПОДПИСКИ",
    ASTROBOT: "Pluto БОТ",
    LOGIN: "ВОЙТИ",
    KUNDLIGPT: "KUNDLI GPT",
    yourHoroscope: "Ваш Гороскоп",
    todaysHoroof: " Сегодняшний гороскоп для",
    horobottomtitle1: "Сегодняшний гороскоп для знаков зодиака",
    horobottomtitle2: "Откройте Свою Космическую Судьбу с Гороскопами AstroGPT",
    horobottomdesc1:
      "Добро пожаловать в царство, где звезды выстраиваются в ряд, а судьбы разворачиваются. Погрузитесь в небесные тайны с Гороскопами AstroGPT.",
    horobottomtitle3: "О Предсказании Гороскопа AstroGPT:",
    horobottomdesc2:
      "Наше Предсказание Гороскопа AstroGPT приносит вечную мудрость астрологии в цифровую эпоху.",
    horobottomtitle4: "Как Сегодняшний Гороскоп Может Помочь Вам:",
    horopoint1:
      "Получите инсайты о потенциальных возможностях и вызовах, которые могут возникнуть в течение дня.",
    horopoint2:
      "Получите персонализированные рекомендации на основе вашего знака зодиака.",
    horopoint3:
      "Найдите ясность и направление в различных аспектах вашей жизни.",
    horopoint4:
      "Используйте свой гороскоп как небесный компас.",
    horopoint5:
      "Примите мудрость звезд.",
    horopoint6:
      "Оставайтесь в гармонии с космическими энергиями вокруг вас.",
    astroKundli: "Pluto Kundli",
    astroBot: "Pluto Bot",
    getAstroInsights: "Получить Астро Инсайты",
    inputname: "Имя",
    birthPlace: "Место рождения",
    birthDistrict: "Район рождения",
    birthTime: "Дата и время рождения",
    gender: "Пол",
    male: "Мужской",
    female: "Женский",
    language: "Язык",
    notfollowing: "Вы никого не подписаны!",
    expFollow: "Исследовать Астрологов",
    following: "Подписки",
    clearFollow: "Очистить Подписки",
    unfollow: "Отписаться",
    ABOUT: "О НАС",
  },
  nl: {
    signIn: "Inloggen",
    signUp: "Registreren",
    signOut: "Uitloggen",
    newtoAstroGPT: "Nieuw bij AstroGPT?",
    password: "Wachtwoord",
    email: "E-mailadres",
    name: "Volledige naam",
    alreadyAcc: "Heeft u al een account?",
    welcome: "Voorbij de Sterren",
    astroGPT: "PlutoAstro",
    finger: "Slimme Spirituele Inzichten",
    gptSearch: "GPT Zoeken",
    loginDescription:"Verbind met astrologen, krijg real-time inzichten, genereer geboortehoroscopen en ontdek je kosmische bestemming.",
    explore: "BluBot",
    chat: "Chat met Astrologen",
    call: "Bel Astrologen",
    search: "Zoek Astrologen",
    filter: "Filter",
    all: "Alle",
    topRated: "Best beoordeeld",
    offer: "Aanbieding",
    vedic: "Vedisch",
    numerology: "Numerologie",
    tarot: "Tarot",
    faceReading: "Gelaatslezen",
    vastu: "Vastu",
    lifeCoach: "Life Coach",
    psychologist: "Psycholoog",
    palmistry: "Handlijnkunde",
    orders: "Bestellingen",
    exp: "Exp",
    years: "Jaren",
    min: "min",
    horoTitle: "Dagelijkse Horoscoop",
    horoDesc:
      "Ontvang dagelijkse horoscoopvoorspellingen en gepersonaliseerde astrologische inzichten om u te helpen weloverwogen beslissingen te nemen, relaties te versterken en nieuwe mogelijkheden te ontgrendelen.",
    Aries: "Ram",
    Taurus: "Stier",
    Gemini: "Tweelingen",
    Cancer: "Kreeft",
    Leo: "Leeuw",
    Virgo: "Maagd",
    Libra: "Weegschaal",
    Scorpio: "Schorpioen",
    Sagittarius: "Boogschutter",
    Capricorn: "Steenbok",
    Aquarius: "Waterman",
    Pisces: "Vissen",
    ourAstrologers: "Onze Astrologen",
    astroDesc: "13000+ Beste Astrologen uit India voor Online Consultatie",
    zodiacTitle: "Ontdek Uw Sterrenbeeld",
    zodiacDesc:
      "Een korte maar inzichtelijke verkenning van de onderscheidende kenmerken en invloeden geassocieerd met elk astrologisch symbool, waardevolle inzichten biedend in persoonlijkheid en levenspaden gebaseerd op geboortedata.",
    zodiacBirth: "Geboortedatum",
    zodiacTime: "Geboortetijd",
    zodiacPlace: "Geboorteplaats",
    zodiacFind: "VIND",
    CHAT: "CHAT",
    CALL: "BEL",
    SIGNOUT: "UITLOGGEN",
    FOLLOWING: "VOLGEND",
    ASTROBOT: "Pluto BOT",
    LOGIN: "INLOGGEN",
    KUNDLIGPT: "KUNDLI GPT",
    yourHoroscope: "Uw Horoscoop",
    todaysHoroof: " Vandaag horoscoop van",
    horobottomtitle1: "Vandaag horoscoop voor sterrenbeelden",
    horobottomtitle2: "Ontgrendel Uw Kosmische Bestemming met AstroGPT Horoscopen",
    horobottomdesc1:
      "Welkom in het rijk waar sterren uitlijnen en bestemmingen zich ontvouwen. Duik in de hemelse mysteries met AstroGPT Horoscopen.",
    horobottomtitle3: "Over AstroGPT Horoscoop Voorspelling:",
    horobottomdesc2:
      "Onze AstroGPT Horoscoop Voorspelling brengt de tijdloze wijsheid van astrologie naar het digitale tijdperk.",
    horobottomtitle4: "Hoe de Horoscoop van Vandaag U Kan Begeleiden:",
    horopoint1:
      "Krijg inzicht in potentiële kansen en uitdagingen die zich gedurende uw dag kunnen voordoen.",
    horopoint2:
      "Ontvang gepersonaliseerde begeleiding gebaseerd op uw sterrenbeeld.",
    horopoint3:
      "Vind duidelijkheid en richting in verschillende aspecten van uw leven.",
    horopoint4:
      "Gebruik uw horoscoop als een hemels kompas.",
    horopoint5:
      "Omarm de wijsheid van de sterren.",
    horopoint6:
      "Blijf afgestemd op de kosmische energieën om u heen.",
    astroKundli: "Pluto Kundli",
    astroBot: "Pluto Bot",
    getAstroInsights: "Ontvang Astro Inzichten",
    inputname: "Naam",
    birthPlace: "Geboorteplaats",
    birthDistrict: "Geboortedistrict",
    birthTime: "Geboortedatum & Tijd",
    gender: "Geslacht",
    male: "Mannelijk",
    female: "Vrouwelijk",
    language: "Taal",
    notfollowing: "Je volgt niemand!",
    expFollow: "Verken Astrologen",
    following: "Volgend",
    clearFollow: "Wis Volgend",
    unfollow: "Ontvolgen",
    ABOUT: "OVER",
  },
  es: {
    signIn: "Iniciar sesión",
    signUp: "Inscribirse",
    signOut: "Desconectar",
    newtoAstroGPT: "¿Nuevo en AstroGPT?",
    password: "Contraseña",
    email: "Dirección de correo electrónico",
    name: "Nombre completo",
    alreadyAcc: "¿Ya tienes una cuenta?",
    welcome: "Cosmic Dive Into",
    astroGPT: "AstroGPT",
    finger: "A Finger Pointing to Reality",
    gptSearch: "Búsqueda GPT",
    loginDescription:
      "Conéctese con astrólogos, chatee sin problemas, obtenga horóscopos personalizados y comience su viaje cósmico hoy mismo con nuestro intuitivo chatbot",
    explore: "Explorar",
    chat: "Chatear con astrólogos",
    call: "Llamar a astrólogos",
    search: "Buscar astrólogos",
    filter: "Filtrar",
    all: "Todos",
    topRated: "Más valorados",
    offer: "Oferta",
    vedic: "Védico",
    numerology: "Numerología",
    tarot: "Tarot",
    faceReading: "Lectura de rostro",
    vastu: "Vastu",
    lifeCoach: "Entrenador de vida",
    psychologist: "Psicólogo",
    palmistry: "Quiromancia",
    orders: "Pedidos",
    exp: "Exp",
    years: "Años",
    min: "min",
    horoTitle: "Horóscopo Diario",
    horoDesc:
      "Sumérgete en el mundo místico de la astrología con nuestra sección completa de horóscopos. Descubre los secretos escritos en las estrellas y desbloquea percepciones sobre tu personalidad, relaciones y futuro.",
    Aries: "Aries",
    Taurus: "Tauro",
    Gemini: "Géminis",
    Cancer: "Cáncer",
    Leo: "Leo",
    Virgo: "Virgo",
    Libra: "Libra",
    Scorpio: "Escorpio",
    Sagittarius: "Sagitario",
    Capricorn: "Capricornio",
    Aquarius: "Acuario",
    Pisces: "Piscis",
    ourAstrologers: "Nuestros Astrólogos",
    astroDesc:
      "Más de 13000 Mejores Astrólogos de la India para Consultas en Línea",
    zodiacTitle: "Conoce tu Signo del Zodiaco",
    zodiacDesc:
      "Una exploración breve pero perspicaz de los rasgos distintivos e influencias asociadas con cada símbolo astrológico, proporcionando percepciones valiosas sobre la personalidad y los caminos de vida basados en fechas de nacimiento.",
    zodiacBirth: "Fecha de Nacimiento",
    zodiacTime: "Hora de Nacimiento",
    zodiacPlace: "Lugar de Nacimiento",
    zodiacFind: "ENCONTRAR",
    CHAT: "CHAT",
    CALL: "LLAMAR",
    SIGNOUT: "CERRAR SESIÓN",
    FOLLOWING: "SIGUIENDO",
    ASTROBOT: "ASTRO BOT",
    KUNDLIGPT: "KUNDLI GPT",
    LOGIN: "INICIAR SESIÓN",
    astroKundli: "Kundli Astro",
    astroBot: "Bot Astro",
    getAstroInsights: "Obtener Astro Insights",
    inputname: "Nombre",
    birthPlace: "Lugar de nacimiento",
    birthDistrict: "Distrito de nacimiento",
    birthTime: "Fecha y hora de nacimiento",
    gender: "Género",
    male: "Masculino",
    female: "Femenino",
    language: "Idioma",
    notfollowing: "¡No estás siguiendo a nadie!",
    expFollow: "Explorar Astrólogos",
    following: "Siguiendo",
    clearFollow: "Limpiar Seguir",
    unfollow: "Dejar de seguir",
    ABOUT: "ACERCA DE",
  },
};

export default lang;